### ISSUE TITLE
关于在spa中angula-ui-router的路由问题

### ISSUE THREAD

**Issue by kylezhang** [atian25/blog#12]
1）业务描述：

打算把微信服务号的部分页面用SPA模式重构下；

2）目前问题：

A：因为只是要把部分页面重构为SPA，所以就涉及到这个SPA的root或者说base href（应该是锚点）怎么定？

B：其实重构的主要是把原来的a标签中的链接，换成ui-sref的形式；原来我的a标签是一个从后台传过来的具体的URL（http://rostname/wx/consultant/home/p/QzkwODVGWWlTRms9/oeOGnuEEc4g5bj2wMaSRJxjx9b_k/939b888800bf4797ba5583dd7aba2463bffcd4c8/0/），

那么现在我该怎么设置这个ui-sref？

怎么设置$stateProvider.state中的各个值；url,templateUrl等。

**Comment by 231907786** [comment]
ui-router的github主页有文档,你问的问题都是ui-router的
