### ISSUE TITLE
使用 vscode@1.6 断点调试 egg cluster

### ISSUE THREAD

**Issue by atian25** [atian25/blog#15]
## 前言

上一次的折腾参见: https://github.com/atian25/blog/issues/14
## 配置

在刚发布的 [vscode 1.6 release note](https://code.visualstudio.com/updates#_debugging) 中, 可以解决该问题, 具体步骤:
- 在项目中按 F5 生成 `.vscode/launch.json` (如果之前有, 先删除)
- 修改生成的文件的 `configurations[0]` 节点, 增加以下信息

``` json
  "runtimeArgs": [
     "--nolazy", "--debug"
  ],
  "port": 5859,
```

![image](https://cloud.githubusercontent.com/assets/227713/19256942/4526edcc-8f9e-11e6-828a-b0bafadc15b4.png)
- 再次 F5 重启
## 遗留问题
- 在 egg-development 自动重启后, 还不能自动重连
- 但从上一次折腾中的收获, 应该是可以写个插件搞定这个事
- 先研究下.

**Comment by atian25** [comment]
发现重启或终止后, egg 进程不会退出, 估计是 cluster 守护的问题, 继续研究下.

**Comment by atian25** [comment]
好像有问题, 重启后端口占用, 之前的进程没退出.
估计是 egg cluster 守护了,  vscode 干不掉, 再研究下

**Comment by atian25** [comment]
1.8 里面可以这么用, 虽然调试体验还是一般.
```json
{
  // Use IntelliSense to find out which attributes exist for node debugging
  // Use hover for the description of the existing attributes
  // For further information visit https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "start egg",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/index.js",
      "cwd": "${workspaceRoot}",
      "runtimeArgs": [
        "--debug"
      ],
      "port": 5859
    },
    {
      "name": "attach worker",
      "type": "node",
      "request": "attach",
      "port": 5858
    },
    {
      "name": "attach agent",
      "type": "node",
      "request": "attach",
      "port": 5856
    }
  ],
  "compounds": [
    {
      "name": "egg debug",
      "configurations": ["start egg", "attach worker", "attach agent"]
    }
  ]
}
```

**Comment by Rwing** [comment]
假如我想debug断点EggCore的构造函数，好像用这个方法不行....

**Comment by atian25** [comment]
嗯, 因为 attach 的太晚了, 这个可以再研究下.

我目前是放弃用 vscode 来 debug, 直接用 webstorm

**Comment by Rwing** [comment]
webstorm可以？可以说说怎么配置吗，我用webstorm也不行啊

**Comment by atian25** [comment]
如图, 无需什么特别配置
![webstorm-debug](https://cloud.githubusercontent.com/assets/227713/21630321/fb4b3cf2-d26a-11e6-98bd-fa890c106dc1.gif)

**Comment by atian25** [comment]
https://code.visualstudio.com/updates/v1_9#_debugging

1.9 版做了些优化，`Nodemon Setup` 和 ` 'restart' option`，有兴趣的同学可以研究下，如何主动 attach 新的 worker debug port

**Comment by atian25** [comment]
更新下，可以直接用 webstorm debug `npm scripts` 了，无需写入口文件。

修改 npm scripts 为:
```json
{
  "dev": "egg-bin dev $NODE_DEBUG_OPTION",
}
```
然后在 webstorm 里面配置一个 npm 的 configuration 即可

![image](https://cloud.githubusercontent.com/assets/227713/23356502/0ce86b86-fd15-11e6-9ca3-d3be596a8c95.png)

**Comment by atian25** [comment]
egg-bin 已经重构，支持传参，最新的 3.0，要去掉 `--`，即：

```
{
   "scripts": {
    "dev": "egg-bin dev $NODE_DEBUG_OPTION",
  }
}
```

**Comment by atian25** [comment]
我擦，vscode 的 debug，支持 The Restart Frame action allows you to re-enter the current function after you have changed variables with the Set Value action

新文档不错
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restart-frame-node

**Comment by BoizZ** [comment]
webstorm启动一些大型例如`node_modules`里面的文件夹层级太多的项目很容易崩

**Comment by atian25** [comment]
@BoizZ 用我们写的 https://github.com/coolme200/webstorm-disable-index

**Comment by BoizZ** [comment]
@atian25 666

**Comment by atian25** [comment]
现在通过 https://github.com/eggjs/egg-development-proxyworker 可以完美实现 vscode debug egg 了。详见：https://eggjs.org/zh-cn/core/development.html#使用-vscode-进行调试

**Comment by j4dream** [comment]
well done

**Comment by huboshu0819** [comment]
完全按照文档来的，vscode里面打断点还是无效0.0

**Comment by atian25** [comment]
@huboshu0819  @okoala 来接客啦~

**Comment by okoala** [comment]
@atian25  你看看那个 PR 有啥问题，没问题就合并掉了吧~

**Comment by huboshu0819** [comment]
真是秒速啊！！

**Comment by okoala** [comment]
@huboshu0819  要不你到官网提 issue， 然后把 vscode 相关打印信息贴出来看看~

**Comment by huboshu0819** [comment]
@okoala 好哇  我等下去提。 这个是打印信息，您可以先看下 
![image](https://user-images.githubusercontent.com/10299842/27077516-df80f2a2-5062-11e7-8014-d9eec1fcbada.png)

**Comment by okoala** [comment]
@huboshu0819  目测是你没有 attach worker 啊 ~

**Comment by atian25** [comment]
没啥问题吧，你在那边 ping 下其他人。好像 ci 挂了。

发自我的 iPhone

**Comment by okoala** [comment]
那个覆盖率问题，我稍后完善，不影响使用~

**Comment by huboshu0819** [comment]
@okoala 刚去官网提了issue，我看配置文件里面我有设置启动 attach worker额。
![image](https://user-images.githubusercontent.com/10299842/27078245-858719a4-5065-11e7-85cb-e4b05101c12c.png)

**Comment by okoala** [comment]
@huboshu0819  直接在官网交流吧~

**Comment by okoala** [comment]
eggjs/egg#1048

**Comment by atian25** [comment]
终于可以宣布该问题完美解决了~

- [使用 egg-bin 调试](https://eggjs.org/zh-cn/core/development.html#%E4%BD%BF%E7%94%A8-egg-bin-%E8%B0%83%E8%AF%95)
- 相关 [[RFC] egg-bin debug](https://github.com/eggjs/egg/issues/1376)
- 后续还会推出一个辅助的 vscode 插件，敬请期待。

**Comment by ChaofengYan** [comment]
![image](https://user-images.githubusercontent.com/6375349/30636408-fe34da38-9dba-11e7-97db-e2b1c617e501.png)

之前还好使的，现在一直报错

**Comment by atian25** [comment]
@ChaofengYan `npm update` 了没? 删除依赖重新安装下.

**Comment by ChaofengYan** [comment]
@atian25 使用egg-init 新建的一个type=simple项目，使用npm i安装依赖，没有lock，依然报同样的错误

**Comment by atian25** [comment]
我试了本地无法复现。

**Comment by atian25** [comment]
终于，今天 VSCode@1.12.0 正式支持了 [Automatically attach debugger to Node.js subprocesses](https://code.visualstudio.com/updates/v1_20#_node-debugging)

我们这个问题可以完美解决了，详细描述参见：https://github.com/atian25/blog/issues/25

**Comment by BoizZ** [comment]
天猪威武
