### ISSUE TITLE
服务器部署npm下载egg-scripts 出错

### ISSUE THREAD

**Issue by llsldwy** [atian25/blog#28]
node V8.4.0
npm V5.3.0
Linux

hi。大神，您好，向您咨询个问题
服务器部署时候，"egg-scripts": "2.5.0"已经制定版本，但是部署时候还是报错，报npm ERR! egistry.npm.taobao.org/egg-scripts/download/egg-scripts-1.1.1.tgz"}," 为啥没有选择2.5.0的egg-scripts版本？最后我尝试用 package-lock.json 文件锁定版本，但还是报这个错误！

![image](https://user-images.githubusercontent.com/6800117/38861765-ea419d68-4265-11e8-8a65-8dbde8a67fe5.png)

**Comment by atian25** [comment]
- egg 问题在 egg issue 讨论。
- 永远不要锁版本，删掉 lock
- 你那个报错是因为你服务端有 lock 文件吧
