### ISSUE TITLE
我用插件debug,每次运行都会卡在两个进程,但是换成同事的项目,就没这个问题.

### ISSUE THREAD

**Issue by chengsitom** [atian25/blog#34]
我用插件debug,每次运行都会卡在两个进程,如图所示. 需要手动点击继续运行.
但是换成同事的项目,就没这个问题.
另外如果直接npm run dev也不会卡住
<img width="581" alt="2019-02-20 10 11 14" src="https://user-images.githubusercontent.com/18043060/53061391-863a1d00-34f8-11e9-977e-c161b04416f7.png">
<img width="739" alt="2019-02-20 10 12 43" src="https://user-images.githubusercontent.com/18043060/53061395-86d2b380-34f8-11e9-91f3-7bf386fb17f7.png">
因为刚接触node.js不久,实在找不到解决方案,劳烦帮忙看看

**Comment by atian25** [comment]
有可能是你的 launch.json 没有配置 `"autoAttachChildProcesses": true`

仔细看下 https://github.com/atian25/blog/issues/25 吧，要了解 Node 的 Debug 原理

**Comment by atian25** [comment]
请提供稳定的复现方式和仓库

**Comment by lixiaolihua** [comment]
https://github.com/eggjs/egg/issues/3534
