### ISSUE TITLE
JD：蚂蚁集团体验技术部 - 前端基础技术

### ISSUE THREAD

**Issue by atian25** [atian25/blog#37]
![image](https://user-images.githubusercontent.com/227713/130033778-7b6a7bf6-676e-40bb-9067-4c18c9fcd41a.png)

## 团队介绍

**我们隶属于 蚂蚁集团体验技术部，负责 前端基础技术，致力于为蚂蚁前端提供 高效省心、稳定可靠 的 Node.js 研发方案及基础设施。**
​

作为一名前端，你是否： 

- 很好奇 玉伯 带领的蚂蚁体验技术部，是如何产出 Ant Design、Egg 等开源项目？ 
- 很好奇 Node.js 如何从小工坊走向大规模企业开发？它如何支撑双十一量级的业务？ 
- 很好奇前端网红的日常？想了解朴老师 AliNode，苏千 CNPM，天猪 Egg 的实践过程吗？ 

现在就加入我们： 

- 你将可以参与到蚂蚁 Node.js 基础设施的建设，参与到蚂蚁前端变革式 Node.js 技术栈建设。
- 你将体验到大规模 Node.js 研发背后的各种黑科技基建，想告诉爸妈蚂蚁森林的背后也有你的一份力么？ 
- 你将在实际生产环境中应用业界前沿技术，引领未来。

因为我们是同类人：

- 我们好奇心强，我们不自我局限，我们除了 Node.js，还深度跨界到上下游的共建，如 Serverless PaaS 、研发平台、前端工程化等。
- 我们信仰前端，我们相信技术能改变世界，我们建设了多个稳定可靠的基础服务，支撑多年双十一，是蚂蚁大部分前台业务的背后支撑之一。
- 我们热爱开源，我们崇尚异步协作，我们为社区贡献了 Egg、CNPM 等开源项目，我们有 Ant Design、Umi、AntV 等兄弟团队提供背靠背依靠。

想跟一帮志同道合的人，站在巨人的肩膀上，去探索和引领广州最前沿的前端技术，做一些有意思的事吗？
​

想了解我们的发展史，传送门：『这些年的体验技术部 · Node.js 基础服务 - 摸爬滚打才不负功名尘土』 [https://www.yuque.com/afx/about/nodejs](https://www.yuque.com/afx/about/nodejs)

## 职位描述

我们不自我局限，可以一杆到底也可以深钻某个领域，包括框架和命令行工具（Node.js）、基础服务（云服务）、基础设施底盘（K8S）等等。

- O1：打造易用、可共建、可持续的 Chair 框架及工具链生态，降低学习成本及运维成本，持续提升开发者幸福感。
- O2：提供稳定、可靠、快速、省心的前端基础设施（File、Render、TNPM 等），勇当二号位，助力及协建更接地气的技术产品。
- O3：深度参与 Node.js 社区生态建设，提供引领时代的最佳实践，培养更多的 Node.js 人才。

Base 地：广州琶洲阿里中心、杭州蚂蚁 A 空间。

## 职位要求

我们希望你是：

- 基础踏实，有一技之长，对某个技术领域有自己的见解。 
- 在实际工作中，有较深的 Java 或 Node.js 实践经验，并掌握云服务的日常运维。 
- 聊起技术就两眼发光，饥渴难耐的求知欲。有一定的技术敏感度和视野。 
- 具备良好的学习能力和问题分析能力，关注社区动态及技术发展趋势，拥抱开源。
- 具有很强的分析和解决复杂问题的能力，有强烈的责任心和使命感，良好的沟通表达能力和团队协作能力。

**Comment by LevyEvans-s** [comment]
校招生有机会吗天ju佬～

**Comment by atian25** [comment]
> 校招生有机会吗天ju佬～

我已经不在蚂蚁了，你可以关注下蚂蚁那边的前锋营和零基础学前端 这 2 个培训营，面对大三和大二学生的，会对校招很有帮助，可以关注 裕波 发的公告。

PS：这几年对校招生来说，是一个 hard mode。
