### ISSUE TITLE
关于如何更改egg调试时候的端口

### ISSUE THREAD

**Issue by l1135677068** [atian25/blog#38]
您好，我现在有一个后端项目用的egg，我想用vscode调试，但是前端监听后端使用的端口是8080，默认egg调试的端口是7001,那么我如何更改这个端口呢？

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/140036417-d424f6c4-fe05-4264-a097-0ff3a50fbbc2.png)

去看 egg 文档
