### ISSUE TITLE
AngularJS进阶实践

### ISSUE THREAD

**Issue by atian25** [atian25/blog#6]
> 之前在[「前端圈-走进UC专场」](http://fequan.com/2014/uc/summary.html)的分享的主题

---
## 全文下载地址：[AngularJS进阶实践.pptx](http://atian25.github.io/files/AngularJS%20%E8%BF%9B%E9%98%B6%E5%AE%9E%E8%B7%B5.pptx)

部分内容预览： 
#### 分享主题

![分享主题](https://cloud.githubusercontent.com/assets/227713/5241801/00e53a38-7961-11e4-966d-25e59c1a4b8c.png)
![章节](https://cloud.githubusercontent.com/assets/227713/5241803/1021eae6-7961-11e4-8901-2c4cd5df4dfb.png)
#### 摆脱思维定势

![摆脱思维定势](https://cloud.githubusercontent.com/assets/227713/5241805/169f9ada-7961-11e4-9c98-51224133cf69.png)

![回忆一下](https://cloud.githubusercontent.com/assets/227713/5241807/1eaf7ec0-7961-11e4-862c-baf64eb04dd5.png)

![总结](https://cloud.githubusercontent.com/assets/227713/5241808/25387986-7961-11e4-9462-e70d40078082.png)

**Comment by jozhi** [comment]
很不错。

**Comment by dayney** [comment]
正在使用中

**Comment by Richar-Dada** [comment]
好棒 还有其他分享么？
