### ISSUE TITLE
量身打造angular开发解决方案

### ISSUE THREAD

**Issue by atian25** [atian25/blog#8]
## 量身打造angular开发解决方案

> 不知不觉，我们团队实践`AngularJS`已经一年多了， 一直使用`grunt`来作为工作流，但它存在不少问题。
> 
> 最近在反复拜读 @fouber 的 [「前端工程系列文章」](https://github.com/fouber/blog)， 发现神器 [FIS](http://fis.baidu.com/)，并希望借此机会，量身打造了一款Angular前端工具。
> 
> 可惜FIS本身的文档还不够完善，内部实现有很多黑盒，于是本文作为踩坑实践后的总结，希望能对后来者有所帮助。
> 
> 本文假定读者是有前端开发经验的工程师，对`angular`有一定的实践经验，且仔细阅读过[「前端工程系列文章」](https://github.com/fouber/blog)。
### 1.为何选择FIS?

> `FIS`是一个构建系统内核，很好的抽象了前端集成解决方案所需的通用工具需求。
> 
> 它补全了前端语言缺少的[三种语言能力](http://fis.baidu.com/docs/more/fis-standard.html)：
> - **资源定位的能力：**使用开发路径进行资源定位，项目发布后转换成部署路径
> - **依赖声明的能力：**声明一个资源依赖另一个资源的能力
> - **资源嵌入的能力：**把一个资源的编译内容嵌入到另一个文件中

每个团队都有自己的应用场景，不能一刀切，所以我们需要量身定制。
`FIS`本身并不与任何后端语言绑定。只有基于FIS实现的具体解决方案才会有具体的规范和技术选型。

因此`FIS`是一个很好的起点，目前已有的定制方案：

| 解决方案 | 描述 |
| --- | --- |
| [fis-plus](http://oak.baidu.com/docs/fis-plus) | 适合百度的业务场景，后台为PHP |
| [scrat](http://scrat-team.github.io/#!/index) | 适合UC大导航的业务场景，后台为NodeJS |
| [spmx](https://github.com/fouber/spmx) | 简单实现对seajs的场景 |
| [jello](http://oak.baidu.com/docs/jello) | Java + Velocity |
| [ng-fis](https://github.com/ng-workflow/ngfis) | 针对`Angular`的场景，即本文实现的方案。<br/>(而我们团队的项目则是基于`ng-fis`之上进行再次封装) |

---
### 2.目录
- [前言](01.md)
- [需求调研和分析](02.md)
- [开发规范和部署规范](03.md)
- [模块化框架](04.md)
- [生态模块](05.md)
- [项目模块](06.md)
- [自动化测试](07.md)
- [脚手架工具](08.md)
- [辅助命令](09.md)
- [小技巧](10.md)
- [用户手册](11.md)
- [总结](12.md)

**Comment by atian25** [comment]
移到 https://github.com/atian25/blog/tree/master/posts/angular-fis 了

**Comment by uooo** [comment]
:+1:
